state_dict_filename: "saved_models/rl_gpt_finetune.pt"
do_sample: true # multinomial sampling
num_beams: 1 # beam search
early_stopping: true # stop when at least num_beams sentences finished per batch
num_beam_groups: 1 # diverse beam search
temperature: 0.7 # temperature sampling
top_k: 400 # top k sampling for multinomial sampling or any other strategy
num_return_sequences: 50 # number of sequences to return
metals_list_file: "utils/metals.txt"
sep_token: "&&"
